services:

  database:
    container_name: btodo_db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    networks:
      - btodo-network
    env_file: .database.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d

networks:
  btodo-network:
    name: btodo-network
    external: true
