services:

  postgresql:
    container_name: btodo_db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    networks:
      - database
    env_file: .database.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d

networks:
  database:
